// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_weather_app/test/features/weather/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_weather_app/core/data/datasources/weather_local_datasource.dart' as _i4;
import 'package:flutter_weather_app/core/data/datasources/weather_remote_datasource.dart' as _i5;
import 'package:flutter_weather_app/core/data/models/weather_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class


/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock implements _i5.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Future<_i6.WeatherModel> getCurrentWeather(String? cityName, String? lang) => (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [cityName, lang],
        ),
        returnValue: _i3.Future<_i6.WeatherModel>.value(_i6.WeatherModel(
          coord: _i6.Coord(lon: 0.0, lat: 0.0),
          weather: [],
          base: '',
          main: _i6.Main(
            temp: 0.0,
            feelsLike: 0.0,
            tempMin: 0.0,
            tempMax: 0.0,
            pressure: 0,
            humidity: 0,
          ),
          visibility: 0,
          wind: _i6.Wind(speed: 0.0, deg: 0),
          clouds: _i6.Clouds(all: 0),
          dt: 0,
          sys: _i6.Sys(
            type: 0,
            id: 0,
            country: '',
            sunrise: 0,
            sunset: 0,
          ),
          timezone: 0,
          id: 0,
          name: '',
          cod: 0,
        )),
      ) as _i3.Future<_i6.WeatherModel>);
}

/// A class which mocks [WeatherLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDataSource extends _i1.Mock implements _i4.WeatherLocalDataSource {
  MockWeatherLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Future<_i6.WeatherModel?> getCachedWeather(String? cityName) => (super.noSuchMethod(
        Invocation.method(
          #getCachedWeather,
          [cityName],
        ),
        returnValue: _i3.Future<_i6.WeatherModel?>.value(),
      ) as _i3.Future<_i6.WeatherModel?>);

  @override
  Future<void> cacheWeather(String? cityName, _i6.WeatherModel? weather) => (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [cityName, weather],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}