name: flutter_weather_app
description: "A Flutter weather application with clean architecture."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  
  # Local packages
  weather_core:
    path: packages/weather_core
  weather_domain:
    path: packages/weather_domain
  weather_data:
    path: packages/weather_data
  weather_localization:
    path: packages/weather_localization
  weather_ui_components:
    path: packages/weather_ui_components

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  bloc_test: ^9.1.7
  dartz: ^0.10.1


flutter:
  # the material Icons class.
  uses-material-design: true
  
