name: flutter_weather_app
description: "A Flutter weather application with clean architecture."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  get_it: ^8.0.0
  injectable: ^2.4.4
  easy_localization: ^3.0.7
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  dartz: ^0.10.1

flutter:
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/translations/
